Added the BankTransaction Savina benchmark
parapluu/encore pull request #761
Opened 2017-03-29 13:51 UTC by EliasC

This will not work on Mac OSX until #760 is merged!

2017-05-31 17:17 UTC, kaeluka requested changes
I found only one small issue. Once it is addressed, I'll merge this happily.

2017-05-31 17:17 UTC, kaeluka commented on src/tests/stress/savina/16.BankTransaction/BankTransaction.enc
> +      new Teller(100, 100000)
the default values should be `1000` and `50000` to correspond to the default values of Savina.

2017-05-31 17:38 UTC, kaeluka commented
This benchmark is, sadly, 10x slower (!!) than most akka benchmarks on my computer.

2017-05-31 22:38 UTC, albertnetymk commented
This PR needs to be resumbitted due to publication of originally private repo, "wants to merge 1 commit into `parapluu:development` from `unknown repository`".

2017-06-01 07:17 UTC, EliasC commented
> This benchmark is, sadly, 10x slower (!!) than most akka benchmarks on my computer.

I would guess that this is due to heavy use of futures to achieve atomicity.

> This PR needs to be resumbitted due to publication of originally private repo

Reopened as #812

2017-06-01 07:17 UTC, closed without merging