Added the forkjoin benchmark
parapluu/encore pull request #778
Opened 2017-04-11 09:16 UTC by kikofernandez

Added the forkjoin benchmark

2017-04-11 09:18 UTC, kikofernandez commented
I have assigned the reviewer as per [README.md in Savina](https://github.com/parapluu/encore/tree/development/src/tests/stress/savina)

2017-04-21 12:11 UTC, supercooldave commented
I don't see any join in this framework, just forking.

2017-04-21 12:45 UTC, kikofernandez commented
true, but that's the Savina name and the direct [translation of this benchmark](https://github.com/shamsimam/savina/blob/master/src/main/scala/edu/rice/habanero/benchmarks/fjcreate/ForkJoinAkkaActorBenchmark.scala)

2017-04-21 12:47 UTC, supercooldave commented
This line
```      AkkaActorState.awaitTermination(system)
```
seems to be `join`.

2017-04-21 12:49 UTC, kikofernandez commented
reading the program carefully, I understand that they send messages and need to wait until all actors have finished their work. This is implicit in Encore, as the program cannot terminate unless all actors have performed their work

2017-04-21 12:53 UTC, supercooldave commented
I won't fight this.
Were the original benchmarks done for Akka? If not, I wonder what they look like.

2017-04-21 13:01 UTC, kikofernandez commented
I didn't get the comment at first and we have discussed this offline. 
The question refers to whether other libraries implement this in the same way. 
If we look at the [benchmark using Habanero](https://github.com/shamsimam/savina/blob/master/src/main/scala/edu/rice/habanero/benchmarks/fjcreate/ForkJoinHabaneroActorBenchmark.scala), they do exactly the same thing I did (no `join` operation involved)

2017-06-19 07:52 UTC, supercooldave requested changes
This will be ready to go after the minor comments have been addressed, and after changing benchmark name from `5.fjcreate` to `5.ForkJoinCreate` (or something appropriate).

2017-06-19 07:52 UTC, supercooldave commented on src/tests/stress/savina/5.fjcreate/ForkJoinConfig.enc
> +    if (res <= 0) then
sin(0) * sin(0) = 0
Why is this an unrealistic value?

2017-06-19 07:52 UTC, supercooldave commented on src/tests/stress/savina/5.fjcreate/Main.enc
> +fun bool_from_int(x: int): bool
why not just `not x == 0`

2017-06-19 08:12 UTC, kikofernandez commented on src/tests/stress/savina/5.fjcreate/Main.enc
> +fun bool_from_int(x: int): bool
> operator 'not' is not defined for values of type 'int'

2017-06-19 08:14 UTC, kikofernandez commented on src/tests/stress/savina/5.fjcreate/ForkJoinConfig.enc
> +    if (res <= 0) then
I didn't make this up :)
[Original code here](https://github.com/shamsimam/savina/blob/master/src/main/java/edu/rice/habanero/benchmarks/fjcreate/ForkJoinConfig.java#L47)

```scala
protected static void performComputation(final double theta) {
    final double sint = Math.sin(theta);
    final double res = sint * sint;
    //defeat dead code elimination
    if (res <= 0) {
        throw new IllegalStateException("Benchmark exited with unrealistic res value " + res);
    }
}
```

2017-06-19 08:22 UTC, supercooldave commented on src/tests/stress/savina/5.fjcreate/Main.enc
> +fun bool_from_int(x: int): bool
Must be `not (x == 0)`

2017-06-19 08:23 UTC, supercooldave commented on src/tests/stress/savina/5.fjcreate/ForkJoinConfig.enc
> +    if (res <= 0) then
Amazing! Someone doesn't know his math.
Okay, just leave it.

2017-06-19 10:02 UTC, kikofernandez commented
i have removed the function `bool_from_int, it was not used

2017-06-19 13:23 UTC, merged