Default field values & default parameters
parapluu/encore pull request #810
Opened 2017-05-30 14:37 UTC by knikamo

We have implemented two new features, _default field values_ and _default parameters_ during our Independent Project in Information Engineering (similar to a bachelor thesis).

**Default field values**
Default field values are assignments added at the top of the init-method during desugaring. Default field values does not work for the main class since the init method is not called. Tobias suggested that he would solve this. There is currently no logic to prevent circular references or other unwanted expressions.

**Default parameters**
For each default parameter in a function/method declaration a new function/method is added during desugaring. During typechecking all function/method calls are adjusted to call the function/method with correct number of arguments. Default parameters work as expected according to the tests we have added.

**General**
We have not done anything with error handling or error messages. For example the error message for wrong number of arguments is now a bit weird since a function/method not always expects a fixed number of arguments.

We have written a few tests for each feature, but probably they do not cover everything.

2017-05-30 16:16 UTC, supercooldave commented
Awesome to see this. Very useful features to have in Encore.

2017-05-31 11:16 UTC, supercooldave commented on src/types/Typechecker/Typechecker.hs
> +-- Karro
What is Karro? 
If this is a comment, it could be removed.

2017-05-31 11:28 UTC, supercooldave commented
There are a number of conflicts with the development branch of Encore. These need to be fixed before we can merge this PR. Do you need help doing that?

2017-05-31 13:42 UTC, kikofernandez commented
hi there! You should do a rebase instead of a merge. If you are unsure about how to do it, let us know. (I am going to check how to fix your conflicts and see if I can push a rebased version. Does this sound good?)

2017-05-31 13:47 UTC, knikamo commented
@kikofernandez aha okay it sounds good, I don't know how to do a rebase

2017-05-31 13:48 UTC, kikofernandez commented on src/parser/Parser/Parser.hs
> +  returnWithEnd Field{fmeta, fmut, fname, ftypr, fexpr}
is this `returnWithEnd Field{fmeta, fmut, fname, ftypr, fexpr}` actually `returnWithEnd Field{fmeta, fmut, fname, ftype, fexpr}`  (misspelling of `ftypr` to `ftype`)

2017-05-31 13:49 UTC, knikamo commented on src/parser/Parser/Parser.hs
> +  returnWithEnd Field{fmeta, fmut, fname, ftypr, fexpr}
yes!

2017-05-31 14:00 UTC, kikofernandez commented
are you on the slack channel? There are some things that I need to explain and are probably not that relevant for the PR (otherwise send me an email to kiko.fernandez@it.uu.se and we continue some details that should be understood before I do this)

2017-05-31 15:28 UTC, kikofernandez requested changes
small number of improvements. Do not fix hem yet, as we are going to do the rebase and other stuff tomorrow.

2017-05-31 15:28 UTC, kikofernandez commented on src/ir/AST/Desugarer.hs
> +nameForArg x = show x
not used. this can be removed

2017-05-31 15:28 UTC, kikofernandez commented on src/ir/AST/Desugarer.hs
> +import Debug.Trace
should be removed, this is only for debugging

2017-05-31 15:29 UTC, kikofernandez commented
there is a binary file that can be removed too

2017-06-01 09:05 UTC, kikofernandez approved these changes

2017-06-01 11:03 UTC, knikamo commented
@kikofernandez helped us with a rebase and fixing the conflicts. The test for default field values in the main class fails, @EliasC is responsible to fix that. 

Error messages are not adjusted to the new features. We are going to add issues about this after the PR is merged (right @EliasC ?)

2017-06-01 11:44 UTC, albertnetymk commented
There was a small discussion on cleaning up the commit history a bit before merging. If there's still some pending changes you would like to do, I think it could be nice to add them while revising the history.

2017-06-01 13:17 UTC, EliasC commented
> The test for default field values in the main class fails, @EliasC is responsible to fix that.

I have this implemented locally now and I believe that it should work out of the box. Should I push the commit directly to this branch?

> Error messages are not adjusted to the new features. We are going to add issues about this after the PR is merged (right @EliasC ?)

Yes please! The most important thing is that the known weaknesses are not forgotten. By creating an issue we increase the chances that someone is going to fix it at some point.

2017-06-01 13:36 UTC, kikofernandez commented
@EliasC I think you should push directly to the branch. I do not want to re-write the history until everything that needs to be fixed has been fixed.

2017-06-01 13:37 UTC, kikofernandez commented
@everyone please let me know when everything is in place (issues have been created, all tests pass, etc) and I will do the interactive rebase to squash some commits together

2017-06-01 14:50 UTC, EliasC commented
I've pushed my addition to make the final test case pass. If CI passes, I'm happy with my addition and will not add anything else. @knikamo gets the final word on when everything is in place.

2017-06-02 07:24 UTC, EliasC commented
@knikamo: Can Kiko merge your commits and push it here? In other words, are you done and won't be adding anything else here?

2017-06-06 17:31 UTC, kikofernandez commented
before merging, it would be good if I can get @casperstr and lowe's github email address, so that their commits are linked to their Github users. I'll wait until I get a confirmation on how to proceed

2017-06-07 07:44 UTC, kikofernandez commented
I believe this is ready for merge @EliasC

2017-06-07 07:44 UTC, kikofernandez commented
do not squash

2017-06-07 07:50 UTC, EliasC commented
👍 @kikofernandez 

I am an author though, so you should press the button 😃

2017-06-07 11:03 UTC, merged